---
title: "chapter-4"
format: html
editor: visual
---

# 4.4 Exercises

```{r}
#install.packages("babynames")
library(babynames)
library(tidyverse)
```

```{r}
glimpse(babynames)
```
```{r}
#This makes the Random_subset for problem 1
Random_subset <- babynames %>%
  filter(year=="2003" & name=="Bilal" & sex =="M" |year=="1999" & name=="Terria" & sex =="F" |year=="2010" & name=="Naziyah" & sex =="F" |year=="1989" & name=="Shawana" & sex =="F" |year=="1989" & name=="Jessi" & sex =="F" |year=="1928" & name=="Tillman" & sex =="M"|year=="1981" & name=="Leslee" & sex =="F" |year=="1981" & name=="Sherise" & sex =="F"|year=="1920" & name=="Marquerite" & sex =="F" |year=="1941" & name=="Lorraine" & sex =="M") 
```

```{r}
Random_subset
```

# Problem 1

## Part 1

```{r}
Random_subset |> select(year, sex, name, n) |>
  filter(n>40) |>
  filter(n<85)
```

## Part 2

```{r}
Random_subset |> filter(nchar(name) == 6)
```

## Part 3

```{r}
Random_subset |> mutate(total = n/prop) |>
  filter(total>1960000 & total<2000000)
```

## Part 4

```{r}
Random_subset |> rename(total = n) |>
  distinct(year)
```

```{r}
#library(tidyr)
??pivot_wider
```

```{r}
library(tidyverse)
library(mdsr)
library(googlesheets4)
gs4_deauth()
hiv_key <- "1kWH_xdJDM4SMfT_Kzpkk-1yuxWChfurZuWYjfmv51EA"
hiv <- read_sheet(hiv_key) |>
  rename(Country = 1) |>
  filter(
    Country %in% c("United States", "France", "South Africa")
  ) |>
  select(Country, `1979`, `1989`, `1999`, `2009`) |>
  unnest(cols = c(`2009`)) |>
  mutate(across(matches("[0-9]"), as.double))
hiv
```

```{r}

```
