---
title: "cleaning-data"
author: "Aryan Raval"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(lubridate)

```

```{r}
head(lakers$date,3)

```

```{r}
# Let's make this into a time object.
lakers$date <-ymd(lakers$date)

lakers_date <- lakers |>
  select(date)
head(lakers_date, 3)
```

```{r}
lakers_time <- ms(lakers$time)
head(lakers_time)S

```

# Add time

```{r}
lakers$date[1]
lakers$date[1] + days(x=12)
```

# Tidyr

## Separate

```{r}
lakers_date |>
  separate_wider_delim(
    cols = date, 
    delim = "-", 
    names = c("year","month","day") )    |>
  head(3)
```

## Unite

```{r}
lakers_types <- lakers |>
  select(type,x,y)
lakers_types 

```

```{r}
lakers_types |>
  drop_na() |>
  head(3)

```

## Setting NA

```{r}
library(openintro)

```

```{r}
yrbss <- yrbss |>
  mutate(text_while_driving_30d = na_if(text_while_driving_30d, "did not drive" ))
glimpse(yrbss)

```


```{r}
yrbss <- yrbss |>
  mutate(helmet_12m = na_if(helmet_12m, "did not ride" ))
glimpse(yrbss$helmet_12m)

```
## Replace strings

```{r}
head(yrbss$hours_tv_per_school_day)
```

```{r}
yrbss$hours_tv_per_school_day<- str_replace_all(
  string = yrbss$hours_tv_per_school_day,
  pattern = c(
    "\\+" = "" , 
    "\\<" = "",
    "do not watch" = 0)
)

yrbss$hours_tv_per_school_day <- as.numeric(yrbss$hours_tv_per_school_day)
yrbss$hours_tv_per_school_day
```

### New Dataset

```{r}
billboard
```

```{r}

```

```{r}

```
